# Generated by Django 3.0.8 on 2020-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='video',
            name='is_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
