# Generated by Django 3.1 on 2020-08-18 13:27

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200724_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
