# Generated by Django 3.1 on 2020-08-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200818_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.language'),
        ),
    ]
