# Generated by Django 3.1 on 2020-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_socialnetwork_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
