# Generated by Django 3.1 on 2020-08-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200822_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='content',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_url',
        ),
        migrations.CreateModel(
            name='VideoTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_translated', models.CharField(default='', max_length=100)),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.language')),
                ('video', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.video')),
            ],
            options={
                'unique_together': {('video', 'language')},
            },
        ),
    ]
