# Generated by Django 3.1 on 2020-09-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200822_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='include_portfolio',
        ),
    ]
