# Generated by Django 3.1 on 2020-09-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200919_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='demo_video',
            field=models.CharField(default='', max_length=255),
        ),
    ]
