# Generated by Django 3.1 on 2020-09-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_service_demo_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceTranslate',
        ),
    ]
