# Generated by Django 3.1 on 2020-09-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_delete_servicetranslate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='demo_video',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
