# Generated by Django 3.1 on 2020-12-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20201224_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='brands_logos/')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
