# Generated by Django 3.1 on 2021-01-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=250)),
                ('reason', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
